### ISSUE TITLE
Copy-pastable text fields in geneset details page

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info-website#24]
It would be useful to be able to copy-paste grayed out (non-editable) fields from gensets, such as the geneset id.

**Comment by vincerubinetti** [comment]
This was fixed in https://github.com/biothings/mygeneset.info-website/pull/25/files#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0L132
