### ISSUE TITLE
Spring cleaning

### ISSUE THREAD

**Issue by vincerubinetti** [biothings/mygeneset.info-website#29]
This project was halted in a somewhat half-finished state back in Summer 2021 (I think). Since then I've discovered many ways I could make this project cleaner. I'd like to finish these up so the app is in a nice clean state before we announce that it's released.

I expect that these items would take no longer than a week. The implementation of the oauth login and writing genesets has taken less than a week, so we are still within our estimates for this project. @cgreene Any objections?

- Convert project to the modern composition API. I did this with Monarch UI, and it was very quick (< 8 hours, and that was a much bigger code base), and had [immense benefits](https://github.com/monarch-initiative/monarch-ui-new/issues/97).
- Offload custom tooltip code to tippy library.
- Maybe offload custom JSON viewer code to [vue-json-loader](https://www.npmjs.com/package/vue-json-viewer)? It was a nice exercise to make my own, but maybe better for maintainability to just use third party.
- Update `vue-cli` stuff. This would fix some weird linting issues, and probably help build issues on later version of node that Ricardo was running into.
- Increase linting threshold to all recommended rules, and fix.
- Rework custom table component to make use of named slots instead of format functions.
- Reorganize view folder structure a bit.
- Be better about showing statuses for queries, like loading and error.
- Get extra information, e.g. the "96,290 genesets created" and the placeholder gray boxes on the home page. Or if we can't get that info right now, just hide those sections for now.
- Aria label for "Try It Out" code box on API page?
- Split gh-actions workflows into tests and deploy, [like in Monarch UI](https://github.com/monarch-initiative/monarch-ui-new/tree/main/.github/workflows)
- make trash/remove icons red, and delete geneset button red
- add way to set flag for api root/baseurl

**Comment by ravila4** [comment]
Regarding the "extra information" bullet point.

- **Getting the total number of genesets:** Fetch https://mygeneset.info/metadata and get the JSON field `stats.total`
- **Number of requests:**  We have google analytics integration in the API, but we may want to hide this field until after launch.
- **Table of recent genesets:** We can sort by date using the `sort` parameter. e.g. `https://mygeneset.info/v1/query?q=author:ravila4&sort=updated`.

The one I'm not sure how to get is "Table of recent queries".

**Comment by ravila4** [comment]
> Regarding the metadata, I want to be able to get a count for the user-created genesets separately from the total. Is this an accurate way to do that (basically subtracting the curated totals from the total-total)

Your method seems accurate. It would get all private and publuc genesets.

Another option (Assuming that the Author field exists for all user-genesets, including anonymous genesets): https://mygeneset.info/v1/query?q=_exists_:author then get the "total" from response. However, this method would only count public user genesets.

**Comment by ravila4** [comment]
We do collect logs about all the requests submitted, so the table of recent/popular requests is doable, however, we may want to wait until we have more usage data in the logs.

> Then, at the top with the spinning DNA icons, we can have "user", "curated", and "total" geneset counts (again so it's not just one number).

Also, it may be nice to have separate geneset counts for each of the data sources.
