### ISSUE TITLE
Anonymous user geneset building

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info-website#30]
Currently, the website's "Build" page allows users to build and download genesets while logged out. There is also a "Create" button that would allow the user to create an "anoymous" geneset in the database, but this feature is not implemented at the moment.

 We need to decide whether we want to support these two Build/Download features, and may need to implement a few things to make this workflows smoother.

**Downloading anonymous genesets** - This is mostly working, and I think it's a good idea to keep.
One thing that could be improved is offloading some of the geneset creation code to the backend. The benefit would be that the data would match exactly what the database would record if the user was logged in. One way to do it is to allow unauthenticated POST requests with the --dry_run flag (This could also be useful for testing). In this case, to download a geneset we simply fetch the JSON from the response, and transform it to csv/tsv/gmx formats if needed.

 **Creating anonymous genesets** - Not supported. Currently returns a 401 Unauthorized Error if user is not logged in. 
If we don't plan to support it, we should remove the button for logged out users, and update the text under the Login page's "Use As Guest" section.
I'm open to discussion into reasons to support it, but I think we would have to address a few questions on the backend namely:
1. If an anonymous user creates a geneset, who can edit/delete it? (Perhaps it could be temporary and auto-delete itself?)
2. How to keep track of changes, and avoid conflicts? e.g. If two people edit the same geneset at the same time.

I'll duplicate this issue in the mygeneset backend repository, to track any changes it may require in the backend.

**Comment by ravila4** [comment]
@vincerubinetti Another option for creating genesets in logged out mode could be to simply store the geneset in local cache. We could display a warning that the genesets will only be stored in the database when the user creates an account.

**Comment by vincerubinetti** [comment]
It was my understanding (and I think Casey's understanding as well) that you'd be able to create anonymous genesets. I think this is a very important feature to have, as it's frustrating to find a tool but then be "locked" behind a login.

As it says on the http://mygeneset.info/login page, this comes with the caveat of not being able to create a private geneset or edit a geneset after it's created.

**Comment by vincerubinetti** [comment]
@cgreene Do you think anonymous (without logging) genesets should be supported?

**Comment by cgreene** [comment]
I agree that having the ability to interact without logging in provides an opportunity to get folks excited. The analogy of pastebin for genesets is pretty on point!
