### ISSUE TITLE
Hardcoded "localhost" in endpoint variables

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info-website#31]
@vincerubinetti We forgot to change "localhost" back to "mygeneset.info" before commiting the latest changes:

https://github.com/biothings/mygeneset.info-website/blob/cd0b3630c69e122d6ffa018fb4b687a430d9a0fd/src/api/index.ts#L3-L4

I wonder if it could be good to setup Vue to read an environment variable (set via github actions), so that in development, it defaults to localhost, but in production, it's automatically configured as "mygeneset.info".

**Comment by ravila4** [comment]
I noticed in our other projects we use a vue.config:
https://github.com/SmartAPI/smartAPI/blob/master/web-app/vue.config.js#L17-L29

**Comment by vincerubinetti** [comment]
I put in a hotfix here: https://github.com/biothings/mygeneset.info-website/commit/2c0d755b302d9e80d0b054cf4dcfa176e7150e4f

As for putting in a flag for the baseurl, I've added that as a bullet point in #29 . Though honestly I think it might be rare for us to want to test things in the same way we did the past week.
