### ISSUE TITLE
Show 'Source' info in geneset details page

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info-website#32]
Curated genesets have a field called 'source' (different from 'author' in user genesets). We could display this info instead of the blank Author field. @vincerubinetti up to you whether you want to rename the field label 'Author / Source', keep both fields, or change the text based on context.

![image](https://user-images.githubusercontent.com/9020496/169909432-3bc11c24-4aea-4a30-b850-094298c72d34.png)

**Comment by vincerubinetti** [comment]
If you're asking about whether it's a good idea to keep the two fields separate in the backend, it seems like it would be a good idea because that could be a convenient way to tell if a geneset is curated or not.

As for the frontend Ill display the source instead of the author when its available.
