### ISSUE TITLE
Final frontend updates

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info-website#38]
1. Display gene count in the 'Browse' and 'Your genesets' tables.
![image](https://user-images.githubusercontent.com/9020496/201188664-fc178396-77c1-4d23-ba86-6bbb36cc0471.png)

2. ~Enable sorting genesets by last updated date~. Sorting not possible, but we can display date. (Perhaps not high priority, but this is now possible) For curated datasets, the last update date can be retrieved from the `src.<datasource_name>.upload_date` field in: https://mygeneset.info/v1/metadata/. User and anonymous genesets should have a `updated` field.

3. Refine user experience when creating anonymous genesets:

- Anonymous users can only create public genesets, so if the user is logged out, it should not be possible to uncheck `visibility: public`.
![image](https://user-images.githubusercontent.com/9020496/201190198-3fa65ebc-8bf5-4edc-b7a8-8661f7abd8d7.png)
- UI behavior after creating anonymous genesets. After a user creates an anonymous geneset, he may want to visit the url of the created geneset. We can either redirect him to the newly created geneset, and expect him to remember the url, or cache  a cookie in his browser and display a list of his recently created genesets in the 'Build' page. Right now, we redirect to the Build page, but no geneset id is displayed, therefore the user loses access to his geneset.

~4. Display Metrics in front page: (Number of requests in last 30 days)~

5. Display dates in "ago" format (with full/precies date on hover).

6. Error status for queries?

7. On creation of new geneset, redirect back to newly created geneset page.

8. Contact Marco about linking to new site from biothings website

9. Add favicons of logo.

**Comment by ravila4** [comment]
I found another bug. The "description" field is being displayed as a list with quotations and square brackets.
![image](https://user-images.githubusercontent.com/9020496/201227243-e5ef3a1c-e458-4410-934f-d24efcf46c88.png)

**Comment by ravila4** [comment]
Update on the issue with "description"  being a list. It looks like it's a bit of both a backend and frontend issue.
The frontend is sending a request body that contains a list in the description field, and the backend is not doing type checking or conversion on that field.

![image](https://user-images.githubusercontent.com/9020496/201252694-26439275-9697-4e91-ab67-4d1d970368e5.png)

What I can do on the backend is convert any list in the description to a string by joining all elements.

**Comment by vincerubinetti** [comment]
Good catch, I updated #39 to fix this and made a comment there.

**Comment by ravila4** [comment]
One more thing. I added support on the backend for creating genesets with multiple species, the set of all taxids for a geneset are stored in the "taxid" field, which can be a list or string. Hovering over individual genes already shows their corresponding taxids.

 It would be good to display the contents of "taxid" field somewhere along with the name and description. I think using scientific names would be best, maybe we could use tooltips to show the actual taxid number and/or other information. 

![Screenshot from 2022-11-11 14-53-12](https://user-images.githubusercontent.com/9020496/201423445-aa005137-8649-4a75-a746-635a5b5a7ff9.png)

https://mygeneset.info/v1/geneset/pb8_aIQBbFFuJZ6hu1G-

**Comment by vincerubinetti** [comment]
I'd probably add this in the "Add section", below the selected genes, since this is what it relates to. I'll have to add another api call to get the scientific name and etc. from just the taxon id. I'm hoping the biothings api can support batch searching for taxons in the same way as the mygene api?

**Comment by ravila4** [comment]
@vincerubinetti Ok, that would also be a good place to put it. It should support batch searching.

**Comment by vincerubinetti** [comment]
Done in https://github.com/biothings/mygeneset.info-website/pull/39/commits/23497c05eaaa171ec0ee64d309c69cf3c9474352

**Comment by ravila4** [comment]
I'm seeing "0 species" in cases when there is a single species. https://deploy-preview-39--my-geneset.netlify.app/geneset/0SHcY4QBaIgae9e9dqIu

**Comment by vincerubinetti** [comment]
There are no taxons in those genes:

![image](https://user-images.githubusercontent.com/8326331/201436318-aa45be5c-3431-45e6-ae75-c42c6f96c6ad.png)

**Comment by ravila4** [comment]
Sorry, the stricture it might be confusing

I have two fields for taxids:

1. A top-level "taxid" field that is always present and can be a list or a string, and contains the set of all unique taxids for all genes in the geneset.
2. Individual "taxid" fields in each gene, but they are only present when the gene contains more than one different organism. I assumed that if the geneset contains only one organism, the user could extrapolate that the toplevel field applies to all genes.

**Comment by vincerubinetti** [comment]
The top level field isn't very useful for me. I need to have the taxon ids on each gene because user's can be editing the selected genes on the page, and the taxon capsules I'm showing there should update.

**Comment by vincerubinetti** [comment]
I think there's a lot of single-case exceptions in these endpoints that make things confusing and unpredictable. I think it's better to keep things simple and consistent, especially since the savings is only 1 number field per gene. And the savings only applies to when there's one species.

**Comment by ravila4** [comment]
Ok, that's a good point. I can add taxid to all genes, but it will require refreshing all the curated data.

**Comment by ravila4** [comment]
One final note, since we are adding `taxid` to all genes, I think we should add it to the list of identifiers that you can download:

![Screenshot from 2022-11-11 15-26-15](https://user-images.githubusercontent.com/9020496/201440509-cd31bbda-ddd3-4bd7-af60-ce38858b9d0a.png)

After this, I think we are good to merge the changes.

**Comment by vincerubinetti** [comment]
To be clear, I can do it via the top level taxon field. I just have to check if it's length 1, and if it is, copy that to each gene. Then from there on out each gene (in the data structures I'm working with in the frontend) is assumed to have a taxon field. It's just that it's weird to have to add an exception to that. But if it will take a long time to update the curated data, maybe we can keep it how it is. On the other hand, I can almost guarantee that someone using the API down the road will be confused or caught off guard by it. I'll leave it up to you.

**Comment by ravila4** [comment]
I can change it, since it would simplify the code, which would be better for the people maintaining. I would also have to update the tests.
The data will take a bit to refresh. (There is one datasource that would run overnight)

**Comment by ravila4** [comment]
It's always better to delete code rather than add it!
