### ISSUE TITLE
Entrez values missing

### ISSUE THREAD

**Issue by gtsueng** [biothings/mygeneset.info-website#49]
They were originally missing in the table, were fixed in https://github.com/biothings/mygeneset.info-website/pull/48

Maybe a similar fix can be applied for the hover/alt text?

**Comment by vincerubinetti** [comment]
This is a backend issue. The mygeneset.info API is not returning `genes.entrezgenes`:
https://mygeneset.info/v1/query?q=GOBP_REGULATION_OF_MRNA_POLYADENYLATION

Whereas mygene.info does return entrez:
https://mygene.info/v3/query?q=11051

Thus in the UI, gene searching will show entrez, and geneset searching/viewing will not.

**Comment by newgene** [comment]
@vincerubinetti in mygeneset API, that `genes.ncbigene` is basically the value from `entrezgene` of MyGene.info API response?

`ncbigene` is the "correct" name, while `entrezgene` is a bit older name for the same thing, so we changed it in mygeneset.

**Comment by vincerubinetti** [comment]
Okay, I had no idea about this. I will change instances of "Entrez" in the frontend to "NCBI".
